//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Game
    {
        public int GameId { get; set; }
        [Display(Name = "Date and Time")]
        public System.DateTime DateTime { get; set; }
        public string Venue { get; set; }
        public Nullable<int> Forfeited { get; set; }
        public Nullable<int> TMemberId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual TMember TMember { get; set; }
    }
}
